admin_controllers:
    resource: ../../src/Controller/Admin/
    type: attribute
    exclude:
        - ../../src/Controller/Admin/SecurityController.php
        - ../../src/Controller/Admin/RestaurantWebController.php
