site:
    resource: ../src/Controller/Site/
    type: attribute

admin_security:
    resource: ../src/Controller/Admin/SecurityController.php
    type: attribute

admin_super_web:
    resource: ../src/Controller/Admin/SuperAdminWebController.php
    type: attribute

admin_restaurant_context:
    resource: ../src/Controller/Admin/RestaurantContextController.php
    type: attribute

admin_restaurant_web:
    resource: ../src/Controller/Admin/RestaurantWebController.php
    type: attribute

admin_media_web:
    resource: ../src/Controller/Admin/MediaWebController.php
    type: attribute

admin_product_web:
    resource: ../src/Controller/Admin/ProductWebController.php
    type: attribute

admin_category_web:
    resource: ../src/Controller/Admin/CategoryWebController.php
    type: attribute

admin_qrcode_web:
    resource: ../src/Controller/Admin/QrCodeWebController.php
    type: attribute

admin_account_web:
    resource: ../src/Controller/Admin/AccountWebController.php
    type: attribute
